apiVersion: v1
kind: Pod
metadata:
  name: fail-3-pending-pod
spec:
  containers:
    - name: hungry-app
      image: nginx:alpine
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
