# Viraj Bhanage — 24BCS10274
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-web
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: recreate-web
  template:
    metadata:
      labels:
        app: recreate-web
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
